<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jordi
 * Date: Thu, 06 Dec 2018 09:07:06 +0000
 */

$conf['title'] = 'L-G-Chimio';
$conf['lang'] = 'fr';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
